services:
 nginx:
  build: ./nginx/
  image: nginx:42
  container_name: nginx
  restart: on-failure
  ports:
   - "443:443"
  depends_on:
   - wordpress
  volumes:
   - /var/www/html:/var/www/html
  networks:
   - inception

 wordpress:
  build: ./wordpress/
  image: wordpress:42
  container_name: wordpress
  restart: on-failure
  expose:
   - "9000"
  volumes:
   - /var/www/html:/var/www/html
  networks:
   - inception

 mariadb:
  build: ./mariadb/
  image: mariadb:42
  container_name: mariadb
  restart: on-failure
  expose:
   - "3306"
  volumes:
    - /home/jburlama/data:/var/lib/mysql
  networks:
   - inception

networks:
 inception:
   driver: bridge
