services:
 nginx:
  build: ./requirements/nginx/
  image: nginx:42
  container_name: nginx
  restart: on-failure
  ports:
   - "443:443"
  depends_on:
   - wordpress
  volumes:
   - wordpress:/var/www/html
  networks:
   - inception
  env_file:
    - .env

 wordpress:
  build: ./requirements/wordpress/
  image: wordpress:42
  container_name: wordpress
  restart: on-failure
  expose:
   - "9000"
  volumes:
   - wordpress:/var/www/html
  networks:
   - inception
  env_file:
    - .env

 mariadb:
  build: ./requirements/mariadb/
  image: mariadb:42
  container_name: mariadb
  restart: on-failure
  expose:
   - "3306"
  networks:
   - inception
  depends_on:
   - nginx
  volumes:
   - mariadb:/var/lib/mysql
  env_file:
    - .env

 redis:
  build: ./requirements/redis/
  image: redis:42
  container_name: redis
  restart: on-failure
  expose:
   - "6379"
  depends_on:
   - nginx
  networks:
   - inception
  volumes:
    - wordpress:/var/www/html
  env_file:
    - .env

 ftp:
  build: ./requirements/ftp/
  image: ftp:42
  container_name: ftp
  restart: on-failure
  ports:
    - "20:20"
    - "21:21"
    - "40000-40005:40000-40005"
  depends_on:
   - wordpress
  networks:
   - inception
  volumes:
    - wordpress:/home/jburlama/ftp/files
  env_file:
    - .env

networks:
 inception:
   driver: bridge


volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/jburlama/data/wordpress
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: /home/jburlama/data/mariadb
      o: bind
