services:
 nginx:
  build: ./requirements/nginx/
  image: nginx:42
  container_name: nginx
  restart: on-failure
  ports:
   - "443:443"
  depends_on:
   - wordpress
  volumes:
   - /home/jburlama/data/wordpress:/var/www/html
  networks:
   - inception

 wordpress:
  build: ./requirements/wordpress/
  image: wordpress:42
  container_name: wordpress
  restart: on-failure
  expose:
   - "9000"
  volumes:
   - /home/jburlama/data/wordpress:/var/www/html
  networks:
   - inception

 mariadb:
  build: ./requirements/mariadb/
  image: mariadb:42
  container_name: mariadb
  restart: on-failure
  volumes:
    - /home/jburlama/data/mariadb:/var/lib/mysql
  expose:
   - "3306"
  networks:
   - inception
  env_file:
    - .env


networks:
 inception:
   driver: bridge
