CREATE DATABASE IF NOT EXISTS wp_site;
CREATE USER IF NOT EXISTS 'jburlama'@'%' IDENTIFIED BY 'Jhonas123!';
GRANT ALL PRIVILEGES ON wp_site.* TO 'jburlama'@'%' IDENTIFIED BY 'Jhonas123!';
FLUSH PRIVILEGES;
